export const itemsTypes = {
    GET_ITEMS: "ITEMS - GET_ITEMS"
}

export const favsTypes = {
    GET_FAVS: "FAVS - GET_FAVS",
    DELETE_FROM_FAVS: "DELETE FROM FAVS - DELETE_FROM_FAVS",
    ADD_TO_FAVS: "ADD TO FAVS - ADD_TO_FAVS",
    FAVS_OPEN: "FAVS OPEN FAVS_OPEN",
    FAVS_CLOSE: "FAVS CLOSE FAVS_CLOSE",
}

export const cartTypes = {
    GET_ORDERS: "ORDERS - GET_ORDERS",
    ADD_TO_CART: "ADD TO CART - ADD_TO_CART",
    DELETE_FROM_CART: "DELETE FROM CART - DELETE_FROM_CART",
    CART_OPEN: "CART OPEN CART_OPEN",
    CART_ClOSE: "CART CLOSE CART_CLOSE",
    CLEAR_CART: "CLEAR CART CLEAR_CART"
}

export const favsModalTypes = {
    OPEN_FAVS_MODAL: "OPEN MODAL - OPEN_FAVS_MODAL",
    CLOSE_FAVS_MODAL: "CLOSE MODAL - CLOSE_FAVS_MODAL",
    OPEN_FAVS_DELETE_MODAL: "OPEN MODAL - OPEN_FAVS_DELETE_MODAL",
    CLOSE_FAVS_DELETE_MODAL: "CLOSE MODAL - CLOSE_FAVS_DELETE_MODAL"
}

export const cartModalTypes = {
    OPEN_CART_MODAL: "OPEN MODAL - OPEN_CART_MODAL",
    CLOSE_CART_MODAL: "CLOSE MODAL - CLOSE_CART_MODAL",
    OPEN_CART_DELETE_MODAL: "OPEN MODAL - OPEN_CART_DELETE_MODAL",
    CLOSE_CART_DELETE_MODAL: "CLOSE MODAL - CLOSE_CART_DELETE_MODAL"
}

export const navigateToNewPageTypes = {
    NAVIGATE_TO_NEW_PAGE: "NAVIGATE TO NEW PAGE - NAVIGATE_TO_NEW_PAGE"
}